/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/Excellent_1803_whitetransparant_2021.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { Mesh } from 'three'

export function Excellent_1803_whitetransparant_2021(props: any) {
  const { nodes, materials } = useGLTF(
    '/Excellent_1803_whitetransparant_2021.gltf'
  );
  return (
    <group {...props} dispose={null}>
      <Mesh geometry={nodes.Cube001.geometry} material={materials.Excellent} />
      <Mesh
        geometry={nodes.Cube001_1.geometry}
        material={materials.Transparan}
      />
    </group>
  );
}

useGLTF.preload('/Excellent_1803_whitetransparant_2021.gltf')
